blog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls')),
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path

from . import views

app_name = "posts"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
]

posts/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    draft = models.BooleanField()
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    publication_date = models.DateTimeField()

    def __str__(self):
        return f"Post: {self.title} ({self.created.strftime('%Y-%m-%d %H:%M')})"

posts/views.py
from django.shortcuts import get_object_or_404, render

from .models import Post


def index(request):
    published_posts = Post.objects.filter(draft=False).order_by('-publication_date')[:20]
    return render(request, 'posts/index.html', {'published_posts': published_posts})


def detail(request, post_id):
    post = get_object_or_404(Post.objects.filter(draft=False), pk=post_id)
    return render(request, 'posts/detail.html', {'post': post})

posts/templates/posts/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Alex's Ramblings</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <link rel="stylesheet" href="{% static 'posts/style.css' %}">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>

<body>
    <nav class="section is-pulled-right">
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="https://github.com/alexd2580">GitHub</a></li>
        </ul>
    </nav>

    <div class="section">
        <h1 class="title">Alex's Ramblings</h1>
    </div>

    <section class="section">
        <div class="container">
            {% block content %} {% endblock %}
        </div>
    </section>

    <footer class="footer">
        <div class="content has-text-centered">
            <p>
                <strong>alex-blog</strong> by <a href="https://github.com/alexd2580">Alexander Dmitriev</a>. The source code is licensed
                <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
            </p>
        </div>
    </footer>
</body>

</html>

posts/templates/posts/detail.html
{% extends 'posts/base.html' %}

{% load markdownify %}

{% block content %}
    <h2 class="is-size-2">{{ post.title }}</h2>
    <article class="post content">
    {{ post.text | markdownify }}
    </article>
{% endblock %}

posts/templates/posts/index.html
{% extends 'posts/base.html' %}

{% block content %}
    {% if published_posts %}
        <ul>
            {% for post in published_posts %}
            <li class="is-size-3">
                <span class="is-size-5">{{ post.publication_date | date:"N d, Y" }}</span>
                <a href="{% url 'posts:detail' post.id %}">{{ post.title }}</a>
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No posts published yet.</p>
    {% endif %}
{% endblock %}